### ISSUE TITLE
Frontend and sometimes Ingest containers fail on the first system start-up

### ISSUE THREAD

**Issue by dtitov** [NBISweden/LocalEGA#127]
**Test case:**
1. Remove you LocalEGA folder.
2. Clone it again.
3. Use new bootstrapping functionality to bring the system up.
4. Run `docker-compose ps`

**E.R.** All containers are up and running.
**A.R.** Frontend and (sometimes) Ingest are down.

Logs for Frontend: 
```
Attaching to ega_frontend
frontend_1    | Processing /root/ega
frontend_1    | Requirement already satisfied: pika==0.10.0 in /usr/lib/python3.6/site-packages (from lega==0.1)
frontend_1    | Requirement already satisfied: aiohttp==2.2.5 in /usr/lib64/python3.6/site-packages (from lega==0.1)
frontend_1    | Requirement already satisfied: pycryptodomex==3.4.5 in /usr/lib64/python3.6/site-packages (from lega==0.1)
frontend_1    | Requirement already satisfied: aiopg==0.13.0 in /usr/lib/python3.6/site-packages (from lega==0.1)
frontend_1    | Requirement already satisfied: colorama==0.3.7 in /usr/lib/python3.6/site-packages (from lega==0.1)
frontend_1    | Requirement already satisfied: aiohttp-jinja2==0.13.0 in /usr/lib/python3.6/site-packages (from lega==0.1)
frontend_1    | Requirement already satisfied: yarl>=0.11 in /usr/lib64/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
frontend_1    | Requirement already satisfied: chardet in /usr/lib/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
frontend_1    | Requirement already satisfied: multidict>=2.1.4 in /usr/lib64/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
frontend_1    | Requirement already satisfied: async-timeout>=1.2.0 in /usr/lib/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
frontend_1    | Requirement already satisfied: psycopg2>=2.5.2 in /usr/lib64/python3.6/site-packages (from aiopg==0.13.0->lega==0.1)
frontend_1    | Requirement already satisfied: jinja2>=2.7 in /usr/lib64/python3.6/site-packages (from aiohttp-jinja2==0.13.0->lega==0.1)
frontend_1    | Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.6/site-packages (from jinja2>=2.7->aiohttp-jinja2==0.13.0->lega==0.1)
frontend_1    | Installing collected packages: lega
frontend_1    |   Running setup.py install for lega: started
frontend_1    |     Running setup.py install for lega: finished with status 'done'
frontend_1    | Successfully installed lega-0.1
frontend_1    | Waiting for database
frontend_1    | Starting the frontend
frontend_1    | [ frontend ][DEBUG ] (L142) Template folder: /usr/lib/python3.6/site-packages/lega/conf/templates
frontend_1    | [ frontend ][ INFO ] (L147) Registering routes
frontend_1    | [ frontend ][ INFO ] (L153) Setting up callbacks
frontend_1    | [ frontend ][ INFO ] (L161) Starting the real deal on <ega_frontend:80>
frontend_1    | Connection error to the Postgres database
frontend_1    |  FATAL:  password authentication failed for user "postgres"
frontend_1    | 
```

Logs for Ingest:
```
Attaching to ega_ingest_1
ingest_1      | Processing /root/ega
ingest_1      | Requirement already satisfied: pika==0.10.0 in /usr/lib/python3.6/site-packages (from lega==0.1)
ingest_1      | Requirement already satisfied: aiohttp==2.2.5 in /usr/lib64/python3.6/site-packages (from lega==0.1)
ingest_1      | Requirement already satisfied: pycryptodomex==3.4.5 in /usr/lib64/python3.6/site-packages (from lega==0.1)
ingest_1      | Requirement already satisfied: aiopg==0.13.0 in /usr/lib/python3.6/site-packages (from lega==0.1)
ingest_1      | Requirement already satisfied: colorama==0.3.7 in /usr/lib/python3.6/site-packages (from lega==0.1)
ingest_1      | Requirement already satisfied: aiohttp-jinja2==0.13.0 in /usr/lib/python3.6/site-packages (from lega==0.1)
ingest_1      | Requirement already satisfied: yarl>=0.11 in /usr/lib64/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
ingest_1      | Requirement already satisfied: chardet in /usr/lib/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
ingest_1      | Requirement already satisfied: multidict>=2.1.4 in /usr/lib64/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
ingest_1      | Requirement already satisfied: async-timeout>=1.2.0 in /usr/lib/python3.6/site-packages (from aiohttp==2.2.5->lega==0.1)
ingest_1      | Requirement already satisfied: psycopg2>=2.5.2 in /usr/lib64/python3.6/site-packages (from aiopg==0.13.0->lega==0.1)
ingest_1      | Requirement already satisfied: jinja2>=2.7 in /usr/lib64/python3.6/site-packages (from aiohttp-jinja2==0.13.0->lega==0.1)
ingest_1      | Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.6/site-packages (from jinja2>=2.7->aiohttp-jinja2==0.13.0->lega==0.1)
ingest_1      | Installing collected packages: lega
ingest_1      |   Running setup.py install for lega: started
ingest_1      |     Running setup.py install for lega: finished with status 'done'
ingest_1      | Successfully installed lega-0.1
ingest_1      | Starting the socket forwarder
ingest_1      | Waiting for Central Message Broker
ingest_1      | Waiting for Local Message Broker
ingest_1      | Waiting for database
ingest_1      | Starting the ingestion worker
ingest_1      | [ingestion ][ INFO ] (L185) With SSL encryption
ingest_1      | [ingestion ][ INFO ] (L189) Retrieving the Master Public Key
ingest_1      | [ingestion ][ INFO ] (L52) Sending request for b'7'
ingest_1      | [ingestion ][ INFO ] (L57) Waiting for answer
ingest_1      | [ingestion ][ INFO ] (L65) Got it
ingest_1      | [ingestion ][ INFO ] (L52) Sending request for b'5'
ingest_1      | [ingestion ][ INFO ] (L57) Waiting for answer
ingest_1      | [ingestion ][ INFO ] (L65) Got it
ingest_1      | [   amqp   ][ INFO ] (L35) Setting hearbeat to 0
ingest_1      | [   amqp   ][ INFO ] (L47) Getting a connection to cega.broker
ingest_1      | [   amqp   ][DEBUG ] (L48) {'host': 'cega_mq', 'port': 5672, 'virtual_host': 'se', 'credentials': <pika.credentials.PlainCredentials object at 0x7f648a583f28>, 'connection_attempts': 2, 'heartbeat_interval': 0}
ingest_1      | Traceback (most recent call last):
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 384, in _handle_read
ingest_1      |     data = self.socket.recv(self._buffer_size)
ingest_1      | ConnectionResetError: [Errno 104] Connection reset by peer
ingest_1      | 
ingest_1      | During handling of the above exception, another exception occurred:
ingest_1      | 
ingest_1      | Traceback (most recent call last):
ingest_1      |   File "/usr/bin/ega-ingest", line 11, in <module>
ingest_1      |     load_entry_point('lega==0.1', 'console_scripts', 'ega-ingest')()
ingest_1      |   File "/usr/lib/python3.6/site-packages/lega/ingest.py", line 202, in main
ingest_1      |     from_broker = (get_connection('cega.broker'), CONF.get('cega.broker','file_queue'))
ingest_1      |   File "/usr/lib/python3.6/site-packages/lega/utils/amqp.py", line 51, in get_connection
ingest_1      |     return pika.BlockingConnection( pika.ConnectionParameters(**params) )
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
ingest_1      |     self._process_io_for_connection_setup()
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
ingest_1      |     self._open_error_result.is_ready)
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
ingest_1      |     self._impl.ioloop.poll()
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 602, in poll
ingest_1      |     self._process_fd_events(fd_event_map, write_only)
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 443, in _process_fd_events
ingest_1      |     handler(fileno, events, write_only=write_only)
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 364, in _handle_events
ingest_1      |     self._handle_read()
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 407, in _handle_read
ingest_1      |     return self._handle_error(error)
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 338, in _handle_error
ingest_1      |     self._handle_disconnect()
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 288, in _handle_disconnect
ingest_1      |     self._adapter_disconnect()
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 95, in _adapter_disconnect
ingest_1      |     super(SelectConnection, self)._adapter_disconnect()
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
ingest_1      |     self._check_state_on_disconnect()
ingest_1      |   File "/usr/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 173, in _check_state_on_disconnect
ingest_1      |     raise exceptions.ProbableAuthenticationError
ingest_1      | pika.exceptions.ProbableAuthenticationError
```

**Comment by dtitov** [comment]
Fixed in https://github.com/NBISweden/LocalEGA/pull/132
